export const BOT_IMAGE_TWEETS = {
  desitech: [
    { image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800", content: "🖥️ The future of Indian IT! Major tech hubs in Bengaluru and Hyderabad are leading global innovation. #TechIndia #Bengaluru" },
    { image: "https://picsum.photos/seed/pexels_546819/800/600", content: "💻 Made in India software is taking over the world. Proud of our devs! #Coding #DeveloperLife #TechIndia" },
    { image: "https://picsum.photos/seed/pexels_3861958/800/600", content: "🤖 Indian AI startups are building custom LLMs to solve local problems. Incredible journey! #AIIndia #Startups" },
    { image: "https://picsum.photos/seed/pexels_2004161/800/600", content: "📊 Bengaluru's silicon valley continues to expand. High-quality tech work culture. #Bengaluru #ITPark" },
    { image: "https://picsum.photos/seed/pexels_1181354/800/600", content: "🚀 Coding bootcamps in Pune and Chennai are training the next generation of engineers. #WebDev #India" }
  ],
  iplupdates: [
    { image: "https://picsum.photos/seed/pexels_3621104/800/600", content: "🏏 IPL 2026 is heating up! The crowd at Wankhede is absolutely electric tonight. #Cricket #IPL2026 #MumbaiIndians" },
    { image: "https://images.unsplash.com/photo-1531415080290-bc98545ab2ef?w=800", content: "⚽ Indian Football Team training hard in Kolkata. Let's support local sports! #BlueTigers #FootballIndia" },
    { image: "https://picsum.photos/seed/pexels_260024/800/600", content: "🏆 National Chess Championship in Chennai. India's chess prodigies are dominating the global stage. #Chess #Gukesh" },
    { image: "https://picsum.photos/seed/pexels_220383/800/600", content: "🏸 PV Sindhu's smash clinic in Hyderabad today. True inspiration! #BadmintonIndia #Sports" },
    { image: "https://picsum.photos/seed/pexels_3621104/800/600", content: "🏏 Sunset match at a local playground in Delhi. Cricket is in our blood. #GullyCricket #DesiSports" }
  ],
  isrodaily: [
    { image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800", content: "🔬 ISRO's Gaganyaan mission preparations are in full swing! India to the stars. 🇮🇳 #ISRO #SpaceMission #Science" },
    { image: "https://picsum.photos/seed/pexels_2150/800/600", content: "🌌 Chandrayaan-4 details leaked! ISRO is planning a sample return mission. #Space #ISRO #Astronomy" },
    { image: "https://picsum.photos/seed/pexels_355938/800/600", content: "🚀 Launchpad view at Sriharikota. The gateway to India's space dreams. #Sriharikota #SpaceLaunch #ISRO" },
    { image: "https://picsum.photos/seed/pexels_41951/800/600", content: "☀️ Aditya-L1 solar observatory sends fresh data on solar wind patterns. Proud moment! #SunMission #Science" },
    { image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800", content: "🛰️ India's navigation satellite system (NavIC) completes integration testing. #NavIC #GPSIndia #Tech" }
  ],
  indiapolitics: [
    { image: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800", content: "🌍 Union Budget 2026 focuses heavily on digital infrastructure and UPI expansion. #IndianPolitics #Budget2026" },
    { image: "https://picsum.photos/seed/pexels_6077368/800/600", content: "🗳️ Incredible voter turnout across states today. The world's largest democracy in action! #Elections #India" },
    { image: "https://picsum.photos/seed/pexels_461940/800/600", content: "🏛️ Rashtrapati Bhavan lit up for national day celebrations. A historic view. #Delhi #Heritage" },
    { image: "https://picsum.photos/seed/pexels_268533/800/600", content: "📄 Key Policy briefing in New Delhi regarding AI safety and regulation in India. #Policy #TechRegulations" },
    { image: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800", content: "🛣️ Gati Shakti masterplan: New highways in Rajasthan and Gujarat are improving connectivity. #Infrastructure" }
  ],
  bollygossip: [
    { image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800", content: "🎬 Shah Rukh Khan's new action thriller trailer just dropped and it broke the internet! #Bollywood #SRK #Entertainment" },
    { image: "https://picsum.photos/seed/pexels_1190298/800/600", content: "🎉 Filmfare Awards 2026: The red carpet looks from Mumbai were absolutely stunning. #Entertainment #Filmfare" },
    { image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800", content: "🍿 Housefull boards back in multiplexes across Delhi and Mumbai! Cinema is back. #TheatreVibe #IndianCinema" },
    { image: "https://picsum.photos/seed/pexels_274937/800/600", content: "💫 Celeb spotting at Mumbai airport. Who's heading to Cannes this season? #BollywoodStyle #Gossip" },
    { image: "https://picsum.photos/seed/pexels_1190298/800/600", content: "🎸 A.R. Rahman Live concert rehearsals in Chennai. It's going to be a grand night. #ARRahman #Concert" }
  ],
  desigamer: [
    { image: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?w=800", content: "🎮 BGMI Championship Finals! Team Soul is dominating right now. #BGMI #EsportsIndia #Gaming" },
    { image: "https://picsum.photos/seed/pexels_7915437/800/600", content: "🏆 India wins big at the Asian Esports tournament! Making the nation proud. #Esports #IndiaGaming #Champions" },
    { image: "https://picsum.photos/seed/pexels_442576/800/600", content: "🖥️ Rate my gaming setup! Finally upgraded to a RTX 4080 card. #GamingRig #DesiGamer #PCSetup" },
    { image: "https://picsum.photos/seed/pexels_194511/800/600", content: "🕹️ Retrogaming zone at Bangalore Comic Con. Super Mario tournaments are still fun! #ComicConIndia" },
    { image: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?w=800", content: "🎧 Live streaming Valorant ranked lobby with the squad. Join the stream! #ValorantIndia #Twitch" }
  ],
  musicindia: [
    { image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800", content: "🎵 Nothing beats a live Arijit Singh concert. Pure magic in Delhi last night! #Music #LiveMusic #ArijitSingh" },
    { image: "https://picsum.photos/seed/pexels_1105666/800/600", content: "🎸 Punjabi music taking over global charts! Diljit Dosanjh sets another record. #PunjabiMusic #IndianMusic" },
    { image: "https://picsum.photos/seed/pexels_144429/800/600", content: "🎹 Rehearsing classical Carnatic compositions on the keyboard. East meets West. #FusionMusic #Carnatic" },
    { image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800", content: "🎤 Recording session at a studio in Chennai. New Tollywood track incoming! #BehindTheScenes #Music" },
    { image: "https://picsum.photos/seed/pexels_1105666/800/600", content: "🥁 Traditional Rajasthani folk music performance at Desert Festival, Jaisalmer. #FolkMusic #India" }
  ],
  indianart: [
    { image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800", content: "🎨 Traditional Madhubani paintings showcased at the National Gallery of Modern Art, Delhi. #IndianArt #Culture" },
    { image: "https://picsum.photos/seed/pexels_102127/800/600", content: "🖌️ The vibrance of Rajasthan captured on canvas. Incredible Indian heritage. #Art #Painting #IncredibleIndia" },
    { image: "https://picsum.photos/seed/pexels_1579708/800/600", content: "🏺 Terracotta pottery workshop in Bengal. Supporting rural craftsmen and sustainable art. #Handicrafts #India" },
    { image: "https://picsum.photos/seed/pexels_1646953/800/600", content: "✏️ Fine charcoal sketch of the Varanasi ghats. Capturing spiritual vibes on paper. #CharcoalArt #Varanasi" },
    { image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800", content: "🕌 Exquisite carvings at a temple in Hampi. Ancient Indian architecture is legendary. #Hampi #History" }
  ],
  travelindia: [
    { image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800", content: "✈️ Flying over the majestic Himalayas. There is no place like Kashmir! #TravelIndia #Kashmir #Wanderlust" },
    { image: "https://picsum.photos/seed/pexels_1539581/800/600", content: "🏝️ Andaman & Nicobar Islands: India's own paradise. Unbelievable beaches. #Travel #Andaman #IncredibleIndia" },
    { image: "https://picsum.photos/seed/pexels_1007427/800/600", content: "🌅 Sunrise over Taj Mahal. A visual that stays in your heart forever. #TajMahal #Agra #ExploreIndia" },
    { image: "https://picsum.photos/seed/pexels_358457/800/600", content: "🏔️ Trekking through the cold desert of Spiti Valley. High altitudes, beautiful roads. #SpitiValley #Trekking" },
    { image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800", content: "🛶 Backwaters of Alleppey, Kerala. Floating houseboats and coconut trees. #GodsOwnCountry #Kerala" }
  ],
  indianfoodie: [
    { image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800", content: "🍕 Trying out the viral Street Style Butter Paneer Pizza in Mumbai! Absolutely delicious. #IndianFood #StreetFood #Mumbai" },
    { image: "https://picsum.photos/seed/pexels_3026808/800/600", content: "☕ Filter Kaapi in Chennai. The only way to start a perfect morning. #Food #FilterCoffee #SouthIndian" },
    { image: "https://picsum.photos/seed/pexels_958545/800/600", content: "🥘 Authentic North Indian Thali with Butter Naan, Daal Makhani and Shahi Paneer. Heavy lunch! #Foodie" },
    { image: "https://picsum.photos/seed/pexels_2474661/800/600", content: "🍛 Hot Samosas and Mint Chutney. Perfect snacks for a rainy monsoon evening. #SamosaTime #MonsoonFood" },
    { image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800", content: "🍬 Assorted Indian sweets: Gulab Jamun, Kaju Katli, and Jalebi. Sugar rush! #FestivalSweets #Desserts" }
  ],
  fitdesi: [
    { image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800", content: "🧘‍♂️ Early morning Yoga session by the Ganges in Rishikesh. Finding inner peace. #YogaLife #Rishikesh #Wellness" },
    { image: "https://picsum.photos/seed/pexels_841130/800/600", content: "💪 Gym culture is booming in India. Consistency is key! #FitnessGoal #WorkoutMotivation #DesiFit" },
    { image: "https://picsum.photos/seed/pexels_2294361/800/600", content: "🏃‍♀️ Delhi Half Marathon prep in full swing. Beautiful morning run! #DelhiRunners #Fitness" },
    { image: "https://picsum.photos/seed/pexels_1552242/800/600", content: "🥗 Diet hack: High-protein Paneer and Chickpea salad. Healthy and desi! #HealthyEating #DietPlan" },
    { image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800", content: "🧘‍♀️ Surya Namaskar routine to activate your body. Daily habits matter. #YogaIndia #Health" }
  ],
  paisaletter: [
    { image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800", content: "📈 BSE Sensex hits an all-time high! The Indian market is showing incredible resilience. #StockMarketIndia #Sensex" },
    { image: "https://picsum.photos/seed/pexels_164501/800/600", content: "💸 Understanding tax savings under the new tax regime. Financial literacy is crucial! #IncomeTax #Savings" },
    { image: "https://picsum.photos/seed/pexels_210600/800/600", content: "📊 Designing a diversified portfolio with Indian mutual funds and gold. #InvestingTips #WealthBuilding" },
    { image: "https://picsum.photos/seed/pexels_6801874/800/600", content: "💰 UPI reaches new milestone. Cashless transactions are the absolute norm now. #FintechIndia #UPI" },
    { image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800", content: "📈 Analyzing mid-cap stocks for long term gains. Trade wisely. #Nifty50 #Trading" }
  ],
  desistartup: [
    { image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800", content: "🚀 Pitch deck review session with Bengaluru founders. The energy is inspiring! #StartupsIndia #VC" },
    { image: "https://picsum.photos/seed/pexels_7376/800/600", content: "💼 Launching a fintech product? India is the most competitive market right now. #Entrepreneurship #Fintech" },
    { image: "https://picsum.photos/seed/pexels_3182773/800/600", content: "💡 Collaboration is the heartbeat of Indian co-working spaces. #BengaluruStartups #Founders" },
    { image: "https://picsum.photos/seed/pexels_1181395/800/600", content: "🖥️ Female founders in India are leading some of the most profitable SaaS companies. #WomenInBusiness" },
    { image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800", content: "🚀 Indian startup ecosystem ranks 3rd globally. Unicorns keep rising! #UnicornIndia #Startups" }
  ],
  bharathistory: [
    { image: "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?w=800", content: "🏛️ Explored the majestic Amer Fort in Jaipur today. The architecture is pure poetry. #BharatHistory #Jaipur" },
    { image: "https://picsum.photos/seed/pexels_2099019/800/600", content: "📜 Rare manuscripts of the Chola Dynasty on display at Tanjore. Mindblown! #CholaEmpire #HistoryIndia" },
    { image: "https://picsum.photos/seed/pexels_2166553/800/600", content: "🕌 Standing before the Qutub Minar. Centuries of history captured in red sandstone. #DelhiHistory #Heritage" },
    { image: "https://picsum.photos/seed/pexels_1007427/800/600", content: "🏰 The ruins of Nalanda University. The oldest center of knowledge in Asia. #Nalanda #AncientIndia" },
    { image: "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?w=800", content: "🏛️ Ajanta & Ellora caves. Exquisite rock-cut sculptures from 2nd century BCE. #HeritageIndia #ArtHistory" }
  ],
  desi_couture: [
    { image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800", content: "👗 Bridal collections: Classic red Banarasi sarees are making a massive comeback. #IndianFashion #EthnicWear" },
    { image: "https://picsum.photos/seed/pexels_2983464/800/600", content: "✨ Festive styling tips: Pairing pastel Kurtas with oxidised silver jewellery. #OOTD #DesiStyle" },
    { image: "https://picsum.photos/seed/pexels_1926769/800/600", content: "👜 Handwoven Lucknowi Chikankari work. The details are simply stunning. #HandloomIndia #Fashion" },
    { image: "https://picsum.photos/seed/pexels_157757/800/600", content: "👠 Indian Mojaris and Juttis to complete your traditional outfit. #Footwear #DesiFashion" },
    { image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800", content: "👗 Modern fusion: Indowestern outfits are dominating college festivals. #FusionStyle #FashionIndia" }
  ],
  gyanpedia: [
    { image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800", content: "📚 Did you know? The game of Snakes and Ladders originated in India as Moksha Patam. #Facts #Gyan #India" },
    { image: "https://picsum.photos/seed/pexels_301920/800/600", content: "🧠 The number zero was introduced by Indian mathematician Aryabhata. #HistoryOfScience #Aryabhata" },
    { image: "https://picsum.photos/seed/pexels_12064/800/600", content: "💡 Sanskrit is considered the mother of many modern Indo-European languages. #Sanskrit #Linguistics" },
    { image: "https://picsum.photos/seed/pexels_356079/800/600", content: "🏫 Takshashila, established in 700 BCE, is recognized as the world's first university. #EducationHistory #India" },
    { image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800", content: "📚 The suspension bridge in Ladakh is the highest altitude bridge in the world. #Trivia #AmazingIndia" }
  ],
  click_desi: [
    { image: "https://images.unsplash.com/photo-1602491453979-04da61459118?w=800", content: "📸 Caught this beautiful Bengal Tiger in Ranthambore today. Majestic! #Photography #Wildlife #Ranthambore" },
    { image: "https://picsum.photos/seed/pexels_51383/800/600", content: "📷 Testing new landscape lens during golden hour at Marine Drive, Mumbai. #MumbaiPhotos #Landscape" },
    { image: "https://picsum.photos/seed/pexels_122400/800/600", content: "📸 Street photography in old Delhi. Capturing the daily hustle of Chandni Chowk. #OldDelhi #StreetPhotography" },
    { image: "https://picsum.photos/seed/pexels_210186/800/600", content: "🌄 Sunset over Western Ghats. Nature's canvas is unparalleled. #WesternGhats #NaturePhotography" },
    { image: "https://images.unsplash.com/photo-1602491453979-04da61459118?w=800", content: "🦚 National bird peacock displaying its feathers in Haryana countryside. Stunning shot! #WildlifeIndia" }
  ],
  desi_wellness: [
    { image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800", content: "🌿 Herbal remedies: Making Kadha with ginger, tulsi, and black pepper to boost immunity. #Ayurveda #Wellness" },
    { image: "https://picsum.photos/seed/pexels_4056535/800/600", content: "🧘 benefits of daily meditation: Calming the mind and reducing cortisol levels naturally. #MentalHealth" },
    { image: "https://picsum.photos/seed/pexels_161599/800/600", content: "🌿 Turmeric and honey: The ancient Golden Milk recipe for post-workout recovery. #DesiWellness #GoldenMilk" },
    { image: "https://picsum.photos/seed/pexels_3616956/800/600", content: "💆‍♀️ Ayurvedic oil massage (Abhyanga) for glowing skin and stress relief. #SelfCare #AyurvedaLife" },
    { image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800", content: "🍵 Drinking copper-charged water in the morning. An ancient wellness practice. #AyurvedicLiving #Health" }
  ],
  cine_masala: [
    { image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800", content: "🍿 Review: The new Telugu epic is a visual masterpiece. Action sequences are 10/10! #CineMasala #Tollywood" },
    { image: "https://picsum.photos/seed/pexels_1117132/800/600", content: "🎥 South Cinema dominates global box office! Pushpa 2 and Kalki break previous records. #BoxOffice #Cinema" },
    { image: "https://picsum.photos/seed/pexels_7991579/800/600", content: "🎬 Mollywood's new indie thriller gets standing ovation at international festivals. #MalayalamCinema" },
    { image: "https://picsum.photos/seed/pexels_436413/800/600", content: "🎥 Celebrated director announces sci-fi collab with Tamil superstar. Massive excitement! #Kollywood" },
    { image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800", content: "🍿 Reliving classic Indian parallel cinema. Masterpieces from Satyajit Ray. #ArtCinema #SatyajitRay" }
  ],
  desi_reads: [
    { image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800", content: "📖 Re-reading Rabindranath Tagore's Gitanjali. The depth of Indian poetry is infinite. #Literature #Tagore" },
    { image: "https://picsum.photos/seed/pexels_159866/800/600", content: "📚 Weekend stack: Contemporary Indian fiction from Arundhati Roy and Amitav Ghosh. #DesiReads #Booktok" },
    { image: "https://picsum.photos/seed/pexels_2908984/800/600", content: "📖 Discovering legendary Hindi poets like Harivansh Rai Bachchan. Beautiful lines. #HindiKavita #Poetry" },
    { image: "https://picsum.photos/seed/pexels_207662/800/600", content: "📚 Visualizing regional Indian mythology retellings. Outstanding worldbuilding. #Mythology #IndianBooks" },
    { image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800", content: "📖 Chanakya's Arthashastra. Timeless wisdom on statecraft, ethics and economics. #Chanakya #AncientReads" }
  ]
};

export const generateSeedData = () => {
  const bots = [
    { username: "desitech", displayName: "Desi Tech Insider", avatar: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800", email: "tech@twiller.local", bio: "India's daily dose of technology news and startups 🇮🇳💻", verified: true, isBot: true },
    { username: "iplupdates", displayName: "IPL & Cricket Updates", avatar: "https://images.unsplash.com/photo-1531415080290-bc98545ab2ef?w=800", email: "sports@twiller.local", bio: "Live cricket coverage and breaking IPL news 🏏🏆", verified: true, isBot: true },
    { username: "isrodaily", displayName: "ISRO Daily", avatar: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800", email: "science@twiller.local", bio: "Exploring India's frontiers in space and science 🚀🛰️", verified: true, isBot: true },
    { username: "indiapolitics", displayName: "India Politics", avatar: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800", email: "politics@twiller.local", bio: "Unbiased political coverage from Delhi and across states 🇮🇳🗳️", verified: true, isBot: true },
    { username: "bollygossip", displayName: "Bolly Gossip", avatar: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800", email: "entertainment@twiller.local", bio: "Bollywood movies, OTT shows, and celebrity news 🎬✨", verified: false, isBot: true },
    { username: "desigamer", displayName: "Desi Gamer", avatar: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?w=800", email: "gaming@twiller.local", bio: "BGMI, Valorant India, and esports coverage 🎮🏆", verified: false, isBot: true },
    { username: "musicindia", displayName: "Music India", avatar: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800", email: "music@twiller.local", bio: "Bollywood, Tollywood, and Punjabi music hits 🎵🎸", verified: true, isBot: true },
    { username: "indianart", displayName: "Indian Art & Culture", avatar: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800", email: "art@twiller.local", bio: "Celebrating India's rich art and heritage 🎨🖼️", verified: false, isBot: true },
    { username: "travelindia", displayName: "Incredible India", avatar: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800", email: "travel@twiller.local", bio: "Explore the beauty of India one state at a time ✈️🚂", verified: false, isBot: true },
    { username: "indianfoodie", displayName: "Desi Foodie Eats", avatar: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800", email: "food@twiller.local", bio: "Street food, curries, and Indian restaurant reviews 🥘🍛", verified: false, isBot: true },
    { username: "fitdesi", displayName: "Fit Desi Life", avatar: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800", email: "fitness@twiller.local", bio: "Indian fitness, yoga guides, and desi diet tips 🧘‍♂️💪", verified: true, isBot: true },
    { username: "paisaletter", displayName: "Paisa Letter", avatar: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800", email: "finance@twiller.local", bio: "Indian stock market, personal finance, and startup investment 📈🇮🇳", verified: true, isBot: true },
    { username: "desistartup", displayName: "Desi Startup Watch", avatar: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800", email: "startup@twiller.local", bio: "Tracking India's unicorn journey, founders, and VC funding 🚀💼", verified: true, isBot: true },
    { username: "bharathistory", displayName: "Bharat History", avatar: "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?w=800", email: "history@twiller.local", bio: "Discover the untold stories of ancient and medieval India 🏛️📜", verified: false, isBot: true },
    { username: "desi_couture", displayName: "Desi Couture", avatar: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800", email: "fashion@twiller.local", bio: "Indian fashion, ethnic wear trends, and bridal styling 👗✨", verified: false, isBot: true },
    { username: "gyanpedia", displayName: "Gyanpedia India", avatar: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800", email: "gyan@twiller.local", bio: "Daily interesting facts, General Knowledge, and educational trivia 📚🧠", verified: true, isBot: true },
    { username: "click_desi", displayName: "Click Desi", avatar: "https://images.unsplash.com/photo-1602491453979-04da61459118?w=800", email: "photo@twiller.local", bio: "India through the lens - photography, landscapes, and wildlife 📸🐅", verified: false, isBot: true },
    { username: "desi_wellness", displayName: "Desi Wellness", avatar: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800", email: "wellness@twiller.local", bio: "Ayurveda, herbal remedies, and traditional Indian self-care 🌿🧘", verified: true, isBot: true },
    { username: "cine_masala", displayName: "Cine Masala", avatar: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800", email: "cinema@twiller.local", bio: "South cinema, regional film news, box office, and reviews 🍿🎥", verified: true, isBot: true },
    { username: "desi_reads", displayName: "Desi Reads", avatar: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800", email: "reads@twiller.local", bio: "Indian literature, poetry, and book recommendations 📖✍️", verified: false, isBot: true }
  ];

  const templates = {
    desitech: [
      "🚀 UPI processes 15 billion transactions in a single month! India's digital payments infrastructure is truly world-class. #UPI #DigitalIndia",
      "💻 TCS, Infosys, and Wipro announce massive hiring drives for AI engineers. The AI wave hits India! #TechIndia #Careers",
      "🔐 Major startup funding news: Bengaluru-based cybersecurity firm raises ₹500 crore in Series B. #StartupsIndia #Tech",
      "📱 Jio announces 6G testing in major metro cities. The future of connectivity is approaching fast. #Jio #TelecomIndia",
      "🌐 ONDC is changing the e-commerce game in India. Have you ordered food through it yet? #ONDC #TechIndia",
      "🤖 Indian AI startup launches indigenous LLM trained on 22 official languages! Massive breakthrough. #AIIndia #Tech",
      "💡 Top IT parks in Hyderabad are expanding to accommodate 1 lakh new techies. #HyderabadTech #ITJobs",
      "🔋 Ola Electric's new solid-state battery facility in Tamil Nadu will be the largest in Asia! #EVIndia #Tech",
      "🎯 Zomato's new feature allows inter-city food delivery within 24 hours. Craving Hyderabad Biryani in Delhi? Done. #Startups #FoodTech",
      "🌟 The Internet of Things is taking over Indian agriculture. Smart farming startups see massive growth! #AgriTech #India",
      "💾 Govt plans new semiconductor fabrication unit in Gujarat. Major boost to local chip manufacturing! #MakeInIndia #Chips",
      "🚀 Bengaluru rises to 8th in global tech startup ecosystem rankings. #BengaluruTech #Startups",
      "📱 Local smartphone manufacturing in Noida peaks, exporting millions of units. #Noida #Electronics",
      "☁️ Major cloud providers setting up dedicated Indian data centers in Mumbai and Hyderabad. #CloudComputing",
      "🛡️ Cyber Surakshit Bharat initiative trains over 50,000 govt workers in defensive security. #CyberSecurity"
    ],
    iplupdates: [
      "🏏 BREAKING: MS Dhoni hints at playing one more IPL season! Thala fans assemble. #CSK #MSDhoni #IPL2026",
      "⚽ Sunil Chhetri's legendary career continues to inspire millions. A true icon of Indian football. #IndianFootball #Sports",
      "🏀 NBA India announces new grassroots academies in Mumbai and Delhi. Basketball is growing! #NBAIndia #Sports",
      "🎾 Rohan Bopanna defies age! Reaches another Grand Slam doubles final. #TennisIndia #Sports",
      "🏃 Neeraj Chopra wins gold again with an incredible 89m throw! The golden boy of Indian athletics. #NeerajChopra #Athletics",
      "🏊 Indian swimmers break 3 national records at the Asian Games. #Swimming #TeamIndia",
      "🏋️ IPL 2026 auction: Who will break the ₹25 crore barrier this year? #IPLAuction #Cricket",
      "🎯 Pro Kabaddi League viewership breaks all records! Season 12 is the biggest yet. #PKL #Kabaddi",
      "🏐 Indian Men's Hockey team defeats Australia 3-2 in a thriller! #HockeyIndia #TeamIndia",
      "⛳ Shubhankar Sharma finishes top 10 at the Open. Great day for Indian golf! #Golf #Sports",
      "🏹 Indian Archery team cleansweeps the world cup stage in Turkey. #Archery #SportsIndia",
      "🏏 Shubman Gill cracks a brilliant century against Australia. Future captain in making! #CricketIndia #INDvAUS",
      "🥊 Lovlina Borgohain claims Gold at the World Boxing Championships in New Delhi. #Boxing #India",
      "♟️ Praggnanandhaa defeats world champion in a classic game. Chess crown coming to India! #ChessIndia",
      "🏃‍♀️ Hima Das wins Gold in women's 400m sprint. Sparking athletic dreams everywhere! #HimaDas #Athletics"
    ],
    isrodaily: [
      "🧬 Indian scientists at IISc develop new rapid-testing kit for tropical diseases. Amazing work! #ScienceIndia #Medical",
      "🚀 ISRO successfully launches 36 satellites in a single mission. Precision and efficiency! #ISRO #Space",
      "🌍 New climate study: India's solar energy capacity surpasses expectations. #RenewableEnergy #India",
      "🦕 Fossils of a new dinosaur species discovered in Gujarat's Narmada valley! #Paleontology #India",
      "🧪 IIT Madras researchers create a revolutionary water purification system using nanomaterials. #Innovation #IIT",
      "🌊 Mangrove restoration project in the Sunderbans is showing incredible results. #Environment #India",
      "🔭 Aditya-L1 solar mission sends back stunning high-res images of solar flares! #ISRO #SunMission",
      "💊 Indian pharma companies leading the way in affordable generic medicines globally. #Pharma #HealthIndia",
      "🧠 AIIMS researchers publish groundbreaking study on neuroscience and yoga. #Health #Science",
      "🌱 National Green Hydrogen Mission attracts ₹1 lakh crore investment. #GreenEnergy #India",
      "🧬 Indigenous vaccine for Dengue enters Phase-III trials at ICMR. #MedicalScience #ICMR",
      "🚀 Gaganyaan crew module finishes ocean escape system tests successfully. #Gaganyaan #SpaceIndia",
      "🌡️ IIT Bombay develops ultra-sensitive thermal sensors for healthcare diagnostics. #TechInnovation",
      "🌊 National Institute of Oceanography discovers underwater ruins in Gulf of Khambhat. #MarineScience",
      "🦁 Gir forest lion population grows by 15% due to new conservation models. #WildlifeScience"
    ],
    indiapolitics: [
      "🗳️ Maharashtra assembly elections date announced. It's going to be a tight contest! #MaharashtraElections #Politics",
      "🌍 PM's global tour strengthens strategic partnerships in Europe and the Middle East. #ForeignPolicy #India",
      "📊 New poll: Infrastructure development remains the top priority for young Indian voters. #IndianPolitics",
      "🤝 India-UK Free Trade Agreement officially signed! A massive boost for exports. #Trade #Economy",
      "📰 Supreme Court issues landmark ruling on digital privacy rights. #SupremeCourt #India",
      "🏛️ Parliament's Monsoon session begins today. Key bills on AI regulation and data protection on the agenda. #Parliament",
      "⚖️ New high-speed rail corridor between Mumbai and Ahmedabad is 80% complete! #Infrastructure #VandeBharat",
      "🌐 India pushes for permanent seat at the UN Security Council with backing from major powers. #UNSC #India",
      "🚨 Heavy rains in Chennai: State government deploys disaster response teams. #ChennaiRains #News",
      "🗺️ Border roads organization completes the world's highest motorable road in Ladakh. #BRO #Ladakh",
      "📉 GST collections hit record ₹1.9 lakh crore this month. Strong economic recovery. #GST #Finance",
      "⚡ Solar subsidy scheme launched for 1 crore households across rural India. #SolarIndia #Renewable",
      "⚖️ Supreme Court directs states to implement police reforms for transparent policing. #LawAndOrder",
      "🌾 Minimum Support Price (MSP) raised for Rabi crops to support local farmers. #AgricultureIndia",
      "🚂 Indian Railways to operationalize 100 new Vande Bharat routes by year-end. #Railways"
    ],
    bollygossip: [
      "🎬 KGF Chapter 3 officially confirmed by Prashanth Neel! The hype is real. #Yash #KGF3 #Tollywood",
      "⭐ Deepika Padukone's look at Cannes is breaking the internet. Absolute Queen! #DeepikaPadukone #Bollywood",
      "📺 Mirzapur Season 4 trailer is out and it looks bloodier than ever. #Mirzapur #AmazonPrime",
      "🎤 National Film Awards 2026: RRR sweeps the technical categories again! #RRR #IndianCinema",
      "🎭 Pushpa 2 box office collections cross ₹1000 crore worldwide! #AlluArjun #Pushpa2",
      "🌟 A.R. Rahman announces a massive world tour starting from Chennai. #ARRahman #Music",
      "📸 Ambani pre-wedding festivities continue to dazzle with global superstars performing! #Bollywood #Trending",
      "🎮 Kalki 2898 AD sequel announced. Indian sci-fi is reaching global standards. #Prabhas #Kalki",
      "🎥 Animal Park (Animal Sequel) begins shooting next month. Ranbir Kapoor is back! #RanbirKapoor #Bollywood",
      "💫 Alia Bhatt signs her next Hollywood project. Making India proud! #AliaBhatt #Cinema",
      "🎤 Diljit Dosanjh collaborates with international pop star for a Punjabi track. #DiljitDosanjh #Music",
      "📺 Panchayat Season 4 leaks hint at a new village rival. Exciting times ahead! #Panchayat",
      "🎬 Kiara Advani and Sidharth Malhotra announce their next romantic comedy together. #SidKiara",
      "🎥 National Award for Best Actor goes to Ranveer Singh for his performance in the sports biopic. #RanveerSingh",
      "🎉 Bollywood star weddings: Intimate ceremony planned in Udaipur next week. #BollywoodWeddings"
    ],
    desigamer: [
      "🎮 BGMI unbanned and breaks concurrent player records on Day 1! #BGMI #GamingIndia",
      "🏆 Indian Valorant team qualifies for VCT Masters! Huge moment for PC gaming. #ValorantIndia #Esports",
      "🎯 Mortal and Scout teaming up for a charity stream this weekend. Tune in! #S8UL #IndianGaming",
      "🕹️ Sony PlayStation 5 Pro sees massive demand in India. Sold out in 10 minutes! #PS5India #Gaming",
      "⚔️ GTA 6 trailer breakdown: Will there be an Indian character? Speculations run wild. #GTA6 #Gaming",
      "🌍 Raji: An Ancient Epic developer announces a new game based on Indian mythology. #IndieGames #India",
      "🎲 Nodwin Gaming announces India's biggest LAN event in Delhi with a ₹5 crore prize pool. #EsportsIndia",
      "🔥 Free Fire India launch officially confirmed for next month! #FreeFire #Gaming",
      "🎮 Indian creators dominating YouTube Gaming globally. Total Gaming hits 50M subs! #YouTubeIndia",
      "🏅 Jonathan Gaming wins Esports Player of the Year at the global awards. #Jonathan #Esports",
      "👾 Steam Deck officially launches in Indian retail stores. Handheld gaming is huge! #SteamDeckIndia",
      "🎮 Call of Duty Mobile National Cup starts tomorrow. Top 16 Indian clans qualified. #CODMobile",
      "🔥 Indian game dev studio receives seed funding from Sony PlayStation. #IndianGameDev #IndieGames",
      "🎮 Minecraft Indian servers see huge traffic spike. Indian players build Taj Mahal in game! #Minecraft",
      "🕹️ retro arcade bar opens in Bengaluru, bringing Pac-Man and pinball back. #BangaloreLife"
    ],
    musicindia: [
      "🎵 Anirudh Ravichander's BGM for the new Thalapathy movie is straight fire! 🔥 #Anirudh #Kollywood",
      "🎸 Coke Studio Bharat season 2 features some incredible indie artists from across the country. #CokeStudio",
      "🎤 Shreya Ghoshal's live concert in London was mesmerizing. The voice of a generation! #ShreyaGhoshal #Music",
      "🎹 Lofi Bollywood mixes are the ultimate study and work vibe. What's your favorite track? #BollywoodLofi",
      "🎼 Spotify India reveals top streamed artist: Arijit Singh remains undisputed #1! #SpotifyIndia #ArijitSingh",
      "🎻 Indian classical fusion bands are getting major traction globally. #IndianClassical #Music",
      "🎧 AP Dhillon drops a surprise EP. Brown Munde magic is back! #PunjabiMusic #APDhillon",
      "🌟 Sunburn Goa 2026 lineup is insane! Martin Garrix and DJ Snake headlining. #SunburnGoa #EDM",
      "🎤 'Naatu Naatu' craze is still alive. A flash mob in Times Square went viral today! #NaatuNaatu #Music",
      "🎵 Gully Boy sparked a revolution. The Indian underground hip-hop scene is thriving! #DesiHipHop #Divine",
      "🎼 Divine and King collaborate on a new rap anthem. Boom! #DesiHipHop #NewRelease",
      "🎸 Local indie rock band from Shillong signs contract with major global label. #ShillongMusic",
      "🎤 Sid Sriram live in Chennai. The acoustic version of Adiye was pure gold! #SidSriram",
      "🎻 Pandit Hariprasad Chaurasia's flute recital in Mumbai was a spiritual experience. #IndianClassical",
      "🎧 Indian DJs dominate the DJ Mag Top 100 list this year. Electro-folk is trending! #EDMIndia"
    ],
    indianart: [
      "🎨 Incredible Tanjore painting exhibition opens in Chennai. The gold foil work is breathtaking! #IndianArt #Tanjore",
      "🖼️ NFT of a digital Raja Ravi Varma recreation sells for millions. #DigitalArt #India",
      "✏️ Mumbai street art mapping project highlights local talent transforming the city's walls. #StreetArtMumbai",
      "🌈 Jaipur Literature Festival 2026 announces a spectacular lineup of global and Indian authors. #JLF #Literature",
      "📸 Raghu Rai's iconic photographs of India over the decades are being exhibited in Paris. #Photography #India",
      "🖌️ Handloom weavers in Varanasi are collaborating with modern fashion designers. Beautiful fusion! #Handloom #Fashion",
      "🏛️ New archaeological discoveries in Harappa rewrite ancient Indian history. #History #Archaeology",
      "🎭 The Prithvi Theatre festival begins next week. A celebration of Indian stagecraft! #Theatre #Mumbai",
      "✍️ Ancient Sanskrit manuscripts digitized and made available to the public for the first time. #Heritage #India",
      "🎨 Sabyasachi's new collection redefines Indian bridal wear for the modern era. #Fashion #Sabyasachi",
      "🖼️ National Gallery of Modern Art, Bangalore, hosts retrospectives on Amrita Sher-Gil. #ModernArt",
      "🏺 Traditional blue pottery making in Jaipur. Keeping the craft alive. #JaipurBluePottery",
      "✏️ Calligraphy workshops for Devanagari script are trending among young artists. #Devanagari #Art",
      "🎭 Kathakali performance in Kochi. The makeup process itself is a masterclass in art. #Kathakali",
      "🎨 Murals of Shekhawati mansions are being restored by local heritage groups. #RajasthanHeritage"
    ],
    travelindia: [
      "✈️ Planning a trip to Meghalaya? Don't miss the Living Root Bridges in Cherrapunji. #TravelIndia #NorthEast",
      "🌍 Vande Bharat sleeper trains introduced! Delhi to Mumbai travel just got incredibly luxurious. #IndianRailways",
      "🏝️ Lakshadweep tourism is booming. The pristine blue waters are a must-visit! #Lakshadweep #IncredibleIndia",
      "🗺️ Backpacking across Rajasthan: Jaipur, Udaipur, Jodhpur, and Jaisalmer. The royal circuit! #Rajasthan",
      "🏔️ Spiti Valley roads are officially open for the summer. Road trip time! #SpitiValley #Himalayas",
      "🌅 Watching the sunrise at the Taj Mahal is an experience everyone should have at least once. #TajMahal #Agra",
      "🎒 Goa is not just about beaches. The spice plantations and old Portuguese architecture are amazing. #GoaTravel",
      "🚂 Exploring the tea gardens of Darjeeling via the toy train. Nostalgia max! #Darjeeling",
      "🏜️ Rann of Kutch festival under the full moon. Truly a magical white desert. #GujaratTourism",
      "🌊 Scuba diving in the Andamans reveals some of the best coral reefs in the world. #Andamans #Scuba",
      "🛶 Houseboat cruise in Kumarakom backwaters is the ultimate relaxing weekend. #KeralaBackwaters",
      "🐆 Saw a leopard family during early morning safari at Kabini wildlife reserve! #Kabini #WildlifeIndia",
      "🕉️ Spiritual journey through the temples of Madurai and Rameshwaram. Majestic gopurams! #TamilNadu",
      "🥾 Valley of Flowers trek in Uttarakhand is now in full bloom. A botanical paradise. #Uttarakhand",
      "🏰 Exploring the massive Mehrangarh Fort in Jodhpur. History speaks in every stone. #Jodhpur"
    ],
    indianfoodie: [
      "🍕 Dosa vs Idli: The ultimate South Indian breakfast debate. Which side are you on? #SouthIndianFood",
      "🍜 Chhole Bhature in Delhi or Vada Pav in Mumbai? The battle of street food titans! #StreetFoodIndia",
      "🌮 Homemade Butter Chicken recipe that beats any restaurant! Thread below 👇 #IndianRecipes",
      "☕ Cutting Chai and Parle-G: The undisputed king of Indian snacks. #ChaiLover #India",
      "🥘 Hyderabadi Biryani is not just food, it's an emotion. Paradise or Bawarchi? #Biryani #Hyderabad",
      "🧁 Exploring the sweet shops of Kolkata. Rasgulla and Sandesh heaven! #BengaliSweets",
      "🥑 A modern twist on traditional Indian cuisine is taking over high-end restaurants. #ModernIndian",
      "🍣 Indian street food vendors innovating with bizarre food combinations. Fanta Maggi, anyone? #WeirdFood",
      "🌶️ The spicy Pani Puri challenge! How many can you eat in one go? #PaniPuri #Golgappa",
      "🍰 Celebrating festivals with food: Gujiya for Holi, Modak for Ganesh Chaturthi, Kaju Katli for Diwali! #IndianFestivals",
      "🍳 Instant Oats Uttapam recipe for a quick and healthy Indian breakfast. #HealthyDesi",
      "🍛 Lucknowi Tunday Kababs that melt in your mouth. Truly historical recipe! #LucknowiFood #Kababs",
      "☕ Tandoori Chai craze hits Pune. The smoky flavor is unbelievable. #ChaiLover #PuneFood",
      "🐟 Traditional Goan Fish Curry with rice by the beach. Vacation food done right. #GoanFood #Foodie",
      "🍲 Warm Moong Dal Halwa is the best dessert for winter nights. Pure ghee goodness! #DesiSweets"
    ],
    fitdesi: [
      "🧘‍♂️ Yoga is not just exercise; it's a way of living. Practice daily. #YogaLife #InternationYogaDay",
      "💪 Traditional Indian wrestling centers (Akhadas) are producing world-class athletes. #WrestlingIndia",
      "🥗 Ditching protein powder for roasted chana and sattu. Traditional superfoods! #Sattu #DesiDiet",
      "🏃‍♂️ Running along Marine Drive at 5 AM. Bengaluru and Mumbai runners are built different. #Fitness",
      "🧠 Mindfulness and Pranayama: How to control anxiety using breathing techniques. #Pranayama",
      "🥗 High-protein paneer bhurji is the ultimate vegetarian muscle building food. #FitnessIndia #Diet",
      "🏋️‍♀️ Indian powerlifters are making waves. Women are lifting heavy! #PowerliftingIndia #WomenFitness",
      "🍵 Warm lemon water and copper-pot water in the morning to alkalize your body. #DesiDetox",
      "🚶‍♂️ 10,000 steps a day challenge. Avoid elevators, walk while taking calls. #DailyHabits #ActiveDesi",
      "🧘‍♀️ Halasana (Plow Pose) for back flexibility and spine health. Practice with care. #YogaExercises",
      "🥗 Sprouted Moong Dal chaat: High fiber, high protein, and zero oil! #HealthyDesiSnacks",
      "💪 Physical fitness is a form of self-respect. Hit the gym today, no excuses! #Motivation",
      "🥊 Boxing academies in Haryana are filled with young champions preparing for the Olympics. #HaryanaSports",
      "🚴‍♂️ Sunday cycling club: Rode 50km from Bangalore to Nandi Hills. Legs are sore but worth it! #Cycling",
      "🧘‍♂️ Vipassana meditation retreats: 10 days of silence is life-changing. #Vipassana #Meditation"
    ],
    paisaletter: [
      "📈 Nifty 50 crosses 23,000 mark. The retail investor revolution in India is here. #MutualFunds #Nifty",
      "💰 Stop keeping your emergency fund in a basic savings account. Use sweep-in FD instead. #PersonalFinance",
      "🏡 Is renting better than buying a house in Tier-1 Indian cities? Math shows renting wins. #RealEstate",
      "💳 Credit card optimization: How to fly for free using reward points in India. #CreditCards #Hacks",
      "📊 Compounding is the 8th wonder of the world. Start your SIP at 22, not 30. #Investing101 #SIP",
      "🇮🇳 Sovereign Gold Bonds (SGB) are the best way to buy gold in India. No making charges! #SGB #Gold",
      "📈 IPO market is red hot. Tech startups listing on BSE see bumper returns. #IPONews #Finance",
      "🏦 How the RBI digital rupee is going to change wholesale banking in India. #DigitalRupee #RBI",
      "💵 Term insurance is a must if you have dependents. Do not mix insurance with investment! #Insurance",
      "📊 Indian corporate earnings beat expectations. Corporate growth drives the economy. #EconomyIndia",
      "📉 Cryptocurrencies vs Indian Stocks: Why equity markets offer stable long-term compounding. #Stocks",
      "🏦 Public Provident Fund (PPF) is still the king of tax-free debt investments. #TaxSavings #PPF",
      "💰 How to build a ₹1 Crore corpus by investing just ₹15,000 monthly. #FinancialFreedom #SIP",
      "📈 Real estate prices in Hyderabad and Bangalore are soaring. Supply cannot match demand. #RealEstate",
      "💵 Demat account registrations cross 150 million. The equity culture is deep in India now! #BSE"
    ],
    desistartup: [
      "🚀 Indian SaaS startups are generating $10B ARR selling to global enterprises. SaaS wave! #SaaS #India",
      "🦄 Peak XV and Sequoia Capital announce new funds for Indian early stage startups. #VCFunding",
      "💡 Startup Hub Bengaluru: Where coffee shop chats turn into multi-million dollar companies. #Bangalore",
      "🚗 EV startups in India are disrupting two-wheeler transit. Ather and Ola leading. #EVStartups",
      "📦 Quick commerce is a global phenomenon, but India's 10-minute delivery is unmatched. #QuickCommerce",
      "🌾 Agritech startups are helping Indian farmers get fair prices using AI supply chains. #AgriTech",
      "🎓 Edtech sector going through consolidation. Focus shifts back to offline hybrid learning. #Edtech",
      "🧬 Deeptech and SpaceTech startups in Chennai raise big funding rounds. #SpaceTech #DeepTech",
      "💡 Bootstrapped startups making ₹100 crore profit are the real heroes of Indian tech. #Bootstrapped",
      "🚀 D2C brands are taking over traditional retail. Made in India cosmetics and snacks. #D2CBrands",
      "💼 Shark Tank India Season 5 registrations are open. Get ready for some amazing pitches! #SharkTank",
      "💡 Bengaluru co-working spaces are overflowing with AI builders. The next big thing is cooking! #AIHub",
      "📦 Logistics tech startups are optimizing interstate cargo movement using GPS APIs. #Logistics",
      "🚀 Indian startup incubators at IITs are turning academic research into commercial successes. #IIT",
      "💼 Founder mental health is becoming a key topic in VC boardrooms. Balance is important! #FounderLife"
    ],
    bharathistory: [
      "🏰 The rock fort of Tiruchirappalli is built on a 3-billion-year-old rock! True geographical marvel. #History",
      "🏛️ Chhatrapati Shivaji Maharaj's naval fort Sindhudurg is an engineering masterpiece of the sea. #MarathaHistory",
      "📜 Chanakya's Nitisastra on administration and economic diplomacy remains highly relevant. #Chanakya",
      "🏛️ The Sun Temple at Konark is structured as a giant chariot with 24 carved stone wheels. #Konark",
      "📜 The Indus Valley Civilization had advanced drainage systems when Europe was in caves. #IVC #History",
      "🏰 Rani ki Vav in Gujarat is a spectacular stepwell built as an inverted temple. #Stepwell #Gujarat",
      "🏛️ Emperor Ashoka's rock edicts spread messages of peace and dharma across ancient Asia. #Ashoka",
      "📜 Brihadeeswarar Temple's top dome is carved from a single 80-ton granite stone. How did they lift it? #Chola",
      "🏰 Golconda Fort's acoustic system: A clap at the gate can be heard at the hilltop pavilion! #Golconda",
      "🏛️ The iron pillar of Delhi has remained rust-free for over 1600 years. Ancient metallurgy! #Delhi",
      "📜 The battle of Talikota and the tragic fall of the glorious Vijayanagara Empire. #HampiHistory",
      "🏰 Lohagad Fort: The iron fort that stood undefeated through decades of Deccan wars. #MarathaHistory",
      "🏛️ Stepwells of Delhi: Agrasen ki Baoli is a beautiful slice of history in the middle of Delhi. #Delhi",
      "📜 The history of Indian spices: How black pepper from Kerala changed global trade routes. #SpiceHistory",
      "🏰 Chittorgarh Fort: The legendary fort of Rajasthan that symbolizes Rajput valor and honor. #Rajasthan"
    ],
    desi_couture: [
      "👗 Styling handspun Khadi shirts with indigo denims for a modern Indian summer look. #Khadi #Fashion",
      "✨ Sabyasachi's new collection celebrates traditional Indian block prints and heavy embroidery. #Sabyasachi",
      "👗 The elegance of a simple cotton Mulmul Kurta during hot humid Indian monsoons. #OOTD #MonsoonFashion",
      "✨ Fusion wear: Pairing crop tops with heavy silk skirts for fusion wedding events. #EthnicWear #Styling",
      "👗 Lucknowi Chikankari Kurtas are a summer essential. Light, breathable, and elegant. #Chikankari",
      "✨ Handloom Day: Celebrating the weavers of Pochampally, Kanjeevaram, and Banaras. #HandloomDay",
      "👗 Sustainable fashion: Upcycling old silk sarees into modern designer jackets. #Upcycle #Fashion",
      "✨ Pastel lehengas are dominating the 2026 wedding season. Ditching the classic red. #BridalTrends",
      "👗 Handcrafted Kohlapuris and Juttis are the perfect footwear for any traditional look. #Mojari #Juttis",
      "✨ Gen-Z is redefining ethnic wear with oversized kurtas and chunky silver jewelry. #StreetstyleIndia",
      "👗 Bandhani and Leheriya dupattas from Rajasthan add a pop of color to any plain outfit. #Bandhani",
      "✨ Menswear revolution: Hand-embroidered sherwanis and Nehru jackets are trending. #MensFashion",
      "👗 Kolkata Fashion Week showcases stunning sustainable jute-based fabrics. #JuteFashion #Sustainable",
      "✨ Organza sarees with floral prints: The ultimate elegant look for summer brunches. #SareeLove",
      "👗 Banarasi brocade pants paired with white shirts: Indo-Western goals! #IndoWestern #Fashion"
    ],
    gyanpedia: [
      "📚 Kumbh Mela is so large that the gathering is visible from space satellite imagery! #AmazingFacts #KumbhMela",
      "🧠 Lonar Lake in Maharashtra was created by a meteor impact over 50,000 years ago! #GeologyIndia",
      "📚 The world's highest post office is located in Hikkim, Himachal Pradesh at 14,400 feet! #Trivia #Himachal",
      "🧠 Shani Shingnapur village in Maharashtra has houses without doors, and zero recorded thefts! #Mysteries",
      "📚 India has the world's largest postal network with over 1.5 lakh post offices. #PostalSystem",
      "🧠 The magnetic hill in Ladakh defies gravity! Vehicles automatically roll uphill when in neutral. #Ladakh",
      "📚 Rabindranath Tagore wrote the national anthems for both India and Bangladesh. #Tagore #Trivia",
      "🧠 The Chenab Bridge in Jammu is the world's highest rail bridge, taller than the Eiffel Tower! #Engineering",
      "📚 The wettest inhabited place on Earth is Mawsynram in Meghalaya, receiving 467 inches of rain. #Geography",
      "🧠 Yoga was developed in ancient India over 5,000 years ago during the Vedic period. #YogaHistory",
      "📚 The first rocket in India was transported on a bicycle to the launchpad in 1963! #ISROHistory #India",
      "🧠 The Taj Mahal changes color depending on the time of day, from pinkish in morning to golden at night. #Taj",
      "📚 Indian railway network carries over 23 million passengers daily, equal to Australia's population. #Railways",
      "🧠 The Loktak Lake in Manipur is the only floating lake in the world, famous for its phumdis. #Manipur",
      "📚 Chail Cricket Ground in Himachal Pradesh, at 2,444 meters, is the highest cricket pitch in the world. #Sports"
    ],
    click_desi: [
      "📸 Captured this stunning Hornbill in the Western Ghats during monsoons. Nature is alive! #Wildlife",
      "📷 Golden hour reflecting on the waters of Dal Lake, Srinagar. Captured on 50mm. #Kashmir #Photography",
      "📸 The colorful chaos of flower markets in Bangalore during early morning. #StreetPhotography #Bangalore",
      "📷 Starry night sky over the cold desert of Spiti. Long exposure photography. #AstroPhotography #Spiti",
      "📸 Portraits of Pushkar camel herders. Every wrinkle tells a beautiful story. #PushkarFair #Portrait",
      "📷 Mist covering the tea estates of Munnar, Kerala. Simply magical. #Munnar #LandscapePhotography",
      "📸 The architectural symmetry of Stepwells in Rajasthan. Photographer's dream! #Stepwells #Architecture",
      "📷 Captured a family of Nilgiri Tahrs in Eravikulam National Park. Rare sighting! #NilgiriTahr #Wildlife",
      "📸 Street food vendors of Kolkata. Capturing the motion of frying piping hot Jalebis. #StreetFood",
      "📷 The blue city of Jodhpur from the top of Mehrangarh Fort. Spectacular scale! #Jodhpur #BlueCity",
      "📸 White salt desert of Rann of Kutch blending with the blue sky. Minimalist capture. #KutchPhotography",
      "📷 Macro photography of dew drops on tea leaves in Darjeeling. #Darjeeling #Macro",
      "📸 Gateway of India framed through the yellow-black taxi window. Classic Mumbai shot. #MumbaiPhotos",
      "📷 The dramatic architecture of Victoria Memorial in Kolkata during sunset. #Kolkata #History",
      "📸 Flame-throated bulbul clicked in Goa's Bhagwan Mahavir Sanctuary. #BirdWatching #Goa"
    ],
    desi_wellness: [
      "🌿 Triphala powder: The ultimate Ayurvedic remedy for digestive health and detox. #Ayurveda #Wellness",
      "🧘 Morning meditation routine: Focus on your breath for 10 minutes to reduce stress. #Mindfulness",
      "🌿 The cooling benefits of drinking fennel and coriander seed water in summer. #AyurvedicLiving",
      "💆‍♂️ Using warm sesame oil for foot massage (Padabhyanga) before sleeping. Deep sleep guaranteed! #SelfCare",
      "🌿 Neem and Tulsi: Natural skin purifiers used in Indian households for generations. #NaturalRemedies",
      "🧘 The benefits of practicing Pranayama (Anulom Vilom) for respiratory capacity. #Pranayama #Yoga",
      "🌿 Replacing white sugar with organic Jaggery (Gur) in tea. Good for digestion and iron. #HealthySwaps",
      "💆‍♂️ Amla juice in the morning: High vitamin C for immunity, hair, and skin health. #SuperfoodsIndia",
      "🌿 Ashwagandha: The powerful adaptogen herb to manage anxiety and fatigue. #AyurvedaLife #Wellness",
      "🧘 Warm ginger tea with honey for throat irritation. Classic grandmother's remedy! #HomeRemedies",
      "🌿 Aloe vera gel freshly harvested from the garden for sunburn and skin hydration. #NaturalBeauty",
      "💆‍♂️ Shirodhara treatment: The relaxing Ayurvedic therapy of pouring warm oil on the forehead. #SpaWellness",
      "🌿 Eating seasonal fruits according to Ritucharya (Ayurvedic seasonal regimen). #HealthyHabits",
      "🧘 Yoga Nidra: 20 minutes of conscious relaxation equivalent to 2 hours of sleep. #YogaNidra",
      "🌿 The healing power of Holy Basil (Tulsi) tea for respiratory wellness. #HerbalTea #Tulsi"
    ],
    cine_masala: [
      "🍿 Review: The new Malayalam thriller keeps you guessing till the very last frame. Brilliant! #CineMasala",
      "🎥 The rise of Kannada cinema: Innovative storytelling and local culture capturing global hearts. #Kantara",
      "🍿 Box office clash: Two major superstars clash this Dussehra. Who will win the ticket window? #BoxOffice",
      "🎥 Director Mani Ratnam's cinematography framing is a masterclass for filmmakers. #ManiRatnam #Cinema",
      "🍿 Classic movies review: Why Sholay remains the ultimate textbook for Indian commercial cinema. #Sholay",
      "🎥 The international appeal of SS Rajamouli: How he puts Indian mythology on the global map. #Rajamouli",
      "🍿 Regional OTT platforms are producing some of the best gritty crime dramas in India. #OTTTrends",
      "🎥 Tamil cinema's indie wave: Young directors producing raw, realistic masterpieces. #Kollywood",
      "🍿 Reliving the music of 90s Bollywood: Rahman, Nadeem-Shravan, and Jatin-Lalit. Pure nostalgia! #90sMusic",
      "🎥 Master actor Kamal Haasan's dedication to prosthetics and character design is legendary. #KamalHaasan",
      "🍿 Debutant director wins national award for their beautiful film on rural education. #NationalAwards",
      "🎥 Telugu cinema's visual effects are reaching Hollywood standards. Big budget sci-fi! #Tollywood",
      "🍿 The charm of single-screen theatres in small towns. The whistles and coin-throwing are unmatched! #SingleScreen",
      "🎥 Documentaries from India are winning major accolades at Oscars and Sundance. #IndianDocumentary",
      "🍿 Musical biopics are the next big trend in Bollywood. Stories of legendary singers. #Biopics"
    ],
    desi_reads: [
      "📖 'The God of Small Things' by Arundhati Roy: A masterclass in lush, poetic prose. #ArundhatiRoy #Reads",
      "📚 Checking out Amitav Ghosh's Ibis Trilogy. Incredible historical fiction of the opium trade. #AmitavGhosh",
      "📖 Reading Munshi Premchand's short stories. The raw depiction of rural Indian life. #Premchand #Hindi",
      "📚 Exploring mythology retellings: Devdutt Pattanaik's books simplify complex epics. #MythologyReads",
      "📖 Vikram Seth's 'A Suitable Boy': A massive family saga that captures post-independence India. #VikramSeth",
      "📚 Modern Indian poetry collection by Jeet Thayil and Dom Moraes. Outstanding imagery. #PoetryDesi",
      "📖 Ruskin Bond's stories of Mussoorie bring back childhood nostalgia of the hills. #RuskinBond",
      "📚 Reading 'The Palace of Illusions' by Chitra Banerjee Divakaruni. Mahabharata from Draupadi's perspective. #Reads",
      "📖 Ghalib's Urdu ghazals: The ultimate collection of love, philosophy, and longing. #UrduShayari #Ghalib",
      "📚 Biographies of Indian scientists and leaders that inspire the youth. Add them to your list! #Inspirational",
      "📖 'Train to Pakistan' by Khushwant Singh: A heartbreaking and powerful partition novel. #KhushwantSingh",
      "📚 Exploring Malayalam literature translations: Masterpieces from Vaikom Muhammad Basheer. #Basheer",
      "📖 'The Guide' by R.K. Narayan: The simple charm of Malgudi and Raju's spiritual journey. #RKNarayan",
      "📚 Poetry of Kabir: Timeless couplets (Dohe) teaching harmony and simple living. #Kabir #Poetry",
      "📖 Reading 'Em and the Big Hoom' by Jerry Pinto. A beautiful, moving novel set in Goa/Mumbai. #JerryPinto"
    ]
  };

  return { bots, templates };
};
